version: '3.8'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 8876:80
        depends_on:
            - app
        container_name: vr_kr_nginx
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/app/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        depends_on:
            - db
        container_name: vr_kr_app
        ports:
            - "5173:5173"
            - "9001:9001"
    db:
        image: mysql:latest
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: vr_kr
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: vr_kr_db
